### PR TITLE
Populating manage members table from db

### LINKED ISSUE #79: Login is broken on dev
When I try to log in on the dev branch (admin@soylentgreen.com) I run into the following error:

```
Error: [mobx-state-tree] Error while converting `{"uid":"admin@soylentgreen.com","isActive":true,"isAdmin":true,"uuid":"ISJlDOgBP7S4jYsBrinwqvaxsOU2","isSuperAdmin":false,"lastName":"Allen","prefix":"Mr.","firstName":"Barry","organizationID":"14gcjXheoe1ptjpn28ZN"}` to `(AnonymousModel | null)`:

    snapshot `{"uid":"admin@soylentgreen.com","isActive":true,"isAdmin":true,"uuid":"ISJlDOgBP7S4jYsBrinwqvaxsOU2","isSuperAdmin":false,"lastName":"Allen","prefix":"Mr.","firstName":"Barry","organizationID":"14gcjXheoe1ptjpn28ZN"}` is not assignable to type: `(AnonymousModel | null)` (No type is applicable for the union), expected an instance of `(AnonymousModel | null)` or a snapshot like `({ uid: string; isAdmin: boolean; isSuperAdmin: boolean; prefix: string; firstName: string; lastName: string; role: string; organizationID: string } | null?)` instead.
    at path "/role" value `undefined` is not assignable to type: `string` (Value is not a string).
    snapshot `{"uid":"admin@soylentgreen.com","isActive":true,"isAdmin":true,"uuid":"ISJlDOgBP7S4jYsBrinwqvaxsOU2","isSuperAdmin":false,"lastName":"Allen","prefix":"Mr.","firstName":"Barry","organizationID":"14gcjXheoe1ptjpn28ZN"}` is not assignable to type: `(AnonymousModel | null)` (Value is not a null), expected an instance of `(AnonymousModel | null)` or a snapshot like `({ uid: string; isAdmin: boolean; isSuperAdmin: boolean; prefix: string; firstName: string; lastName: string; role: string; organizationID: string } | null?)` instead.
    at fail$1 (http://localhost:8080/dist/app.bundle.js:65149:12)
    at typecheck (http://localhost:8080/dist/app.bundle.js:64796:15)
    at typecheckInternal (http://localhost:8080/dist/app.bundle.js:64782:9)
    at Array../node_modules/mobx-state-tree/dist/mobx-state-tree.module.js.ModelType.willChange (http://localhost:8080/dist/app.bundle.js:66852:13)
    at interceptChange (http://localhost:8080/dist/app.bundle.js:71527:37)
    at ObservableObjectAdministration../node_modules/mobx/lib/mobx.module.js.ObservableObjectAdministration.write (http://localhost:8080/dist/app.bundle.js:72541:26)
    at Object.set [as user] (http://localhost:8080/dist/app.bundle.js:72774:29)
    at http://localhost:8080/dist/app.bundle.js:2913:17
    at Generator.next (<anonymous>)
    at http://localhost:8080/dist/app.bundle.js:65586:51
```

### PR DESCRIPTION
**Pull request by therealnikhil**
- Pulls list of members from db to populate manage members table
- Closes #79 (broken login)

### CODE REVIEW

File: client/src/components/Firebase/firebase.js [hunk 1]
```diff
@@ -69,11 +69,24 @@ class Firebase {
       const orgDocument = await this.firestore.doc(`organizations/${orgid}`).get();
 
       return orgDocument.data()
-    } catch (err) {
+    } catch (error) {
       console.error("Error fetching organization", error);
     }
   };
 
+  getMembersOfOrg = async orgid => {
```
Comment (ibeckermayer) [inline client/src/components/Firebase/firebase.js:77]: Can we make `origid` be `organizationID`. In general I think its clearer if we use abbreviations sparingly, and also makes it clear that this `organizationID` corresponds precisely to that in the db.

Comment (therealnikhil) [reply client/src/components/Firebase/firebase.js:77]: `orgID` should make it clear enough. I'll make the change.

Comment (therealnikhil) [reply client/src/components/Firebase/firebase.js:77]: Being concise when it's clear. Capitalization should do the trick
